# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Original client_id for rsldev: "be8e8039e18f100d31437e7c4dcfe1b0"
client_id="2395c3c88218a921f255ce0e3de32342"

name = "RSL Services - Logistics"
application_url = "https://rsl-services-logistics.fly.dev"
embedded = true
handle = "rsl-services-logistics"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_locations,read_orders,read_returns,write_app_proxy,write_customers,write_discounts,write_inventory,write_locales,write_locations,write_orders,write_price_rules,write_products,write_returns"

[auth]
redirect_urls = [
  "https://rsl-services-logistics.fly.dev/auth/callback",
  "https://rsl-services-logistics.fly.dev/auth/shopify/callback",
  "https://rsl-services-logistics.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
