# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be8e8039e18f100d31437e7c4dcfe1b0"
name = "RSL Services"
application_url = "https://rsl-services-app.fly.dev"
embedded = true
handle = "rsl-services-app"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_locations,read_orders,read_returns,write_customers,write_inventory,write_locales,write_locations,write_orders,write_products,write_returns,write_discounts,write_app_proxy,write_price_rules"

[auth]
redirect_urls = [
  "https://rsl-services-app.fly.dev/auth/callback",
  "https://rsl-services-app.fly.dev/auth/shopify/callback",
  "https://rsl-services-app.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
