# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be8e8039e18f100d31437e7c4dcfe1b0"
name = "RSL Services"
handle = "rsl-services-1"
application_url = "https://alter-crown-regulation-dealer.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,write_inventory,write_locales,write_locations,write_products"

[auth]
redirect_urls = [
  "https://alter-crown-regulation-dealer.trycloudflare.com/auth/callback",
  "https://alter-crown-regulation-dealer.trycloudflare.com/auth/shopify/callback",
  "https://alter-crown-regulation-dealer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
