api_version = "2025-07"

[[extensions]]
uid = "1fb5bc74-94cc-81fb-1695-ffa8213f668f640c4691"
type = "ui_extension"
name = "Returns Extension"
handle = "returns-extension"
description = "RSL returns data entry block"

[[extensions.targeting]]
module = "./src/blockExtension.jsx"          # EXACT filename & path
target = "admin.order-details.block.render"
