[[extensions]]
name = "Update DB from Return"
handle = "update-db-from-return"
type = "flow_action"
uid = "3ded7773-2377-04fe-f801-007466c35bcd369e7bfd"
description = "Your description"
runtime_url = "https://url.com/api/execute"

[settings]

  [[settings.fields]]
  type = "customer_reference"
  required = true

  [[settings.fields]]
  type = "single_line_text_field"
  key = "your-field-key"
  name = "Display name"
  description = "A description of my field"
  required = true
