[[extensions]]
name = "Update DB from Return"
uid = "3ded7773-2377-04fe-f801-007466c35bcd369e7bfd"
type = "flow_action"
handle = "update-db-from-return"
description = "Update Prisma with Return details"
runtime_url = "https://rsl-services.fly.dev/flow.actions.update-db-from-return"

[settings]
[[settings.fields]]
type = "single_line_text_field"
key = "returnId"
name = "Return ID"
required = true

